spring.application.name=identity
server.port=8082

spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://localhost:5434/identity_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

security.service-jwt-secret=#CAR_RENTAIL_